{% set name = "flytekitplugins-pandera" %}
{% set version = "1.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-pandera-{{ version }}.tar.gz
  sha256: bd72536745f9a09c5a7d31dda79387bd755ee23d6ea81e959cec4048910c2263

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - flytekit >=1.0.0b3,<1.2.0
    - pandera >=0.7.1

test:
  imports:
    - flytekitplugins.pandera
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/flytekitplugins-pandera/
  summary: Pandera plugin for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Pandera plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-pandera/](https://pypi.org/project/flytekitplugins-pandera/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-pandera

extra:
  recipe-maintainers:
    - sugatoray
